server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://lmxdxl99.com.cn/Gym?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.milotnt.entity
  mapper-locations: classpath:/mapper/*.xml